/*
 * generated by Xtext 2.32.0
 */
package org.mdsd.lorescript.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mdsd.lorescript.LoreScriptRuntimeModule;
import org.mdsd.lorescript.LoreScriptStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LoreScriptIdeSetup extends LoreScriptStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LoreScriptRuntimeModule(), new LoreScriptIdeModule()));
	}
	
}
