/*
 * generated by Xtext 2.32.0
 */
package org.mdsd.lorescript.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.mdsd.lorescript.loreScript.LoreScript
import java.util.List
import org.eclipse.xtext.EcoreUtil2
import org.mdsd.lorescript.loreScript.InformationEvent
import org.mdsd.lorescript.loreScript.ChoiceEvent
import org.mdsd.lorescript.loreScript.StringExp
import org.mdsd.lorescript.loreScript.StringLiteral
import org.mdsd.lorescript.loreScript.Scenario
import org.mdsd.lorescript.loreScript.ConcatExp
import org.mdsd.lorescript.loreScript.MultiplyExp
import org.mdsd.lorescript.loreScript.GetFunction
import org.mdsd.lorescript.loreScript.Event

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class LoreScriptGenerator extends AbstractGenerator {
	
	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		/*
		for (e : resource.allContents.toIterable.filter(Event)) {
			fsa.generateFile(
				e.name + ".java",
				e.compile)
		}
		*/
    	val root = resource.contents.head   // root EObject
    	val scenarios = EcoreUtil2.getAllContentsOfType(root, Scenario)
    	val events = EcoreUtil2.getAllContentsOfType(root, Event)
    	val getFunctions = EcoreUtil2.getAllContentsOfType(root, GetFunction)

		val loreScript = resource.contents.head as LoreScript
		if (getFunctions.length > 0) {
			fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptGetHandler.java", compileGetInterface());
		}
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptScenario.java", loreScript.compileScenarioCommon);
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptEvent.java", loreScript.compileEventCommon);
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptOption.java", compileOption);
		
		for (e : events) {
			switch e.type {
				InformationEvent: {
					fsa.generateFile("org/mdsd/lorescript/generated/LoreScript" + e.name + "Event.java", loreScript.compileInformationEvent(e));
				}
				ChoiceEvent: {
					fsa.generateFile("org/mdsd/lorescript/generated/LoreScript" + e.name + "Event.java", loreScript.compileChoiceEvent(e));
				}
			}
		}
		
		fsa.generateFile("org/mdsd/lorescript/generated/" + loreScript.name + ".java", loreScript.compile(scenarios, getFunctions));
	}
	
	private def compile(LoreScript ls, List<Scenario> scenarios, List<GetFunction> getFunctions) '''
		package org.mdsd.lorescript.generated;
		import java.util.ArrayList;
		import java.util.List;
		import java.util.Scanner;
		
		public class «ls.name» {
			«IF getFunctions.length > 0»
			public final LoreScriptGetHandler getHandler;
			«ENDIF»
			
			private LoreScriptScenario currentScenario;
			private LoreScriptEvent next;
			private List<LoreScriptScenario> scenarios = new ArrayList<LoreScriptScenario>();
			public final Scanner scanner = new Scanner(System.in);
			
			«IF getFunctions.length == 0»
			public «ls.name»() {
				Create();
				currentScenario = scenarios.get(0);
				next = currentScenario.getEvent(0);
			}
			«ELSE»
			public «ls.name»(LoreScriptGetHandler getHandler) {
				Create();
				this.getHandler = getHandler;
				currentScenario = scenarios.get(0);
				next = currentScenario.getEvent(0);
			}
			«ENDIF»
			
			private void Create() {
				«FOR s : scenarios»
					LoreScriptScenario «s.name.toLowerCase» = new LoreScriptScenario("«s.name»");
					«FOR e : s.events»
						«s.name.toLowerCase».addEvent(new LoreScript«e.name»Event());
					«ENDFOR»
					scenarios.add(«s.name.toLowerCase»);
				«ENDFOR»
			}
			
			public void run() {
				while (next != null)
					next.run(this);
					
				scanner.close();
			}
			
			public void setNext(String nextEventName) {
				if (nextEventName == null) {
					next = null;
					return;
				}
				
				next = currentScenario.getEvent(nextEventName);
			}
			
			public void setNext(String nextScenarioName, String nextEventName) {
				for (LoreScriptScenario s : scenarios) {
					if (s.name.equals(nextScenarioName)) {
						currentScenario = s;
						next = s.getEvent(nextEventName);
						return;
					}
				}
			}
		}
	'''
	
	private def compileScenarioCommon (LoreScript ls) '''
		package org.mdsd.lorescript.generated;
		import java.util.ArrayList;
		import java.util.List;
		
		public class LoreScriptScenario {
			String name;
			private List<LoreScriptEvent> events = new ArrayList<LoreScriptEvent>();
			
			public LoreScriptScenario (String name) {
				this.name = name;
			}
			
			public void addEvent(LoreScriptEvent event) {
				events.add(event);
			}
			
			public LoreScriptEvent getEvent(String name) {
				for (LoreScriptEvent lse : events) {
					if (lse.name.equals(name)) {
						return lse;
					}
				}
				return null;
			}
			
			public LoreScriptEvent getEvent(int index) {
				return events.get(index);
			}
		}
	'''
	
	private def compileEventCommon (LoreScript ls) '''
		package org.mdsd.lorescript.generated;
		
		public abstract class LoreScriptEvent {
			String name;
			
			public LoreScriptEvent(String name) {
				this.name = name;
			}
			
			public abstract void run(«ls.name» ls);
		}
	'''
	
	private def compileInformationEvent(LoreScript ls, Event e) '''
		«val ie = e.type as InformationEvent»
		package org.mdsd.lorescript.generated;
		
		public class LoreScript«e.name»Event extends LoreScriptEvent{
			«IF ie.goto === null»
				private String transitionScenario = null;
				private String transitionEvent = null;
			«ELSEIF ie.goto.transitionScenario === null»
				private String transitionScenario = null;
				private String transitionEvent = "«ie.goto.transitionEvent.name»";
			«ELSE»
				private String transitionScenario = "«ie.goto.transitionScenario.name»";
				private String transitionEvent = "«ie.goto.transitionEvent.name»";
			«ENDIF»
			
			public LoreScript«e.name»Event() {
				super("«e.name»");
			}
			
			@Override
			public void run(«ls.name» ls) {
				String text = «compileStringExp(ie.text)»;
				System.out.println(text);
				
				if (transitionScenario == null) {
					ls.setNext(transitionEvent);
				}
				else {
					ls.setNext(transitionScenario, transitionEvent);
				}
			}
		}
	
	'''
	
	private def compileChoiceEvent(LoreScript ls, Event e) '''
		«val ce = e.type as ChoiceEvent»
		
		package org.mdsd.lorescript.generated;
			
		public class LoreScript«e.name»Event extends LoreScriptEvent {			
			public LoreScript«e.name»Event() {
				super("«e.name»");
			}
			
			@Override
			public void run(«ls.name» ls) {				
				String text = «compileStringExp(ce.text)»;
				System.out.println(text);
								
				LoreScriptOption[] options = new LoreScriptOption[«ce.options.length»];
				«FOR pair : ce.options.indexed»
					«IF pair.value.goto.transitionScenario === null»
						options[«pair.key»] = new LoreScriptOption(«compileStringExp(pair.value.text)», null, "«pair.value.goto.transitionEvent.name»");
					«ELSE»
						options[«pair.key»] = new LoreScriptOption(«compileStringExp(pair.value.text)», "«pair.value.goto.transitionScenario.name»", "«pair.value.goto.transitionEvent.name»");
					«ENDIF»
				«ENDFOR»
				for (int i = 0; i < options.length; i++) {
					System.out.println("["+(i+1)+"] " + options[i].text);
				}
				
				int choice = 0;
				while(true) {
					try {
						choice = Integer.parseInt(ls.scanner.nextLine());
						String transitionScenario = options[choice-1].transitionScenario;
						String transitionEvent = options[choice-1].transitionEvent;
						
						if (transitionScenario == null) {
							ls.setNext(transitionEvent);
						}
						else {
							ls.setNext(transitionScenario, transitionEvent);
						}
						break;
					}
					catch (NumberFormatException e) {
						System.out.println("Your answer must be a number!");
					}
					catch (ArrayIndexOutOfBoundsException  e) {
						System.out.println("Your answer was not a valid option!");
					}
				}
			}
		}
	'''
	
	private def compileOption() '''
		package org.mdsd.lorescript.generated;
		
		public class LoreScriptOption {
			public String text;
			public String transitionScenario;
			public String transitionEvent;
			public LoreScriptOption(String text, String transitionScenario, String transitionEvent) {
				this.text = text;
				this.transitionScenario = transitionScenario;
				this.transitionEvent = transitionEvent;
			}
		}
	'''
	
	private def compileGetInterface() '''
		package org.mdsd.lorescript.generated;
	
		public interface LoreScriptGetHandler {
			public String get(String request);
		}
	'''
	
	def CharSequence compileStringExp(StringExp exp) {
	    switch exp {
	    	StringLiteral:
	            '''"«exp.value»"'''
	            
	        ConcatExp:
	        	'''«compileStringExp(exp.left)» + «compileStringExp(exp.right)»'''
	        	
	        MultiplyExp: {
	            val repeated = (1 .. exp.multiplier)
	                .map[compileStringExp(exp.left).toString]
	                .join(" + ")
	
	            '''(«repeated»)'''
        	}
        	GetFunction:
        		'''ls.getHandler.get("«exp.request»")'''
        	
	        default:
	            '''""'''
	    }
	}
}
