/*
 * generated by Xtext 2.32.0
 */
package org.mdsd.lorescript.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.mdsd.lorescript.loreScript.LoreScript
import java.util.List
import org.eclipse.xtext.EcoreUtil2
import org.mdsd.lorescript.loreScript.InformationEvent
import org.mdsd.lorescript.loreScript.ChoiceEvent
import org.mdsd.lorescript.loreScript.StringExp
import org.mdsd.lorescript.loreScript.StringLiteral
import org.mdsd.lorescript.loreScript.Scenario
import org.mdsd.lorescript.loreScript.ConcatExp
import org.mdsd.lorescript.loreScript.MultiplyExp

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class LoreScriptGenerator extends AbstractGenerator {
	
	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		/*
		for (e : resource.allContents.toIterable.filter(Event)) {
			fsa.generateFile(
				e.name + ".java",
				e.compile)
		}
		*/
    	val root = resource.contents.head   // root EObject
    	val scenarios = EcoreUtil2.getAllContentsOfType(root, Scenario)
    	//val events = EcoreUtil2.getAllContentsOfType(root, Event)

		val loreScript = resource.contents.head as LoreScript
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptEvent.java", loreScript.compileEventCommon);
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptScenario.java", loreScript.compileScenarioCommon);
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptOption.java", compileOption);
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptInformationEvent.java", loreScript.compileInformationEvent);
		fsa.generateFile("org/mdsd/lorescript/generated/LoreScriptChoiceEvent.java", loreScript.compileChoiceEvent);
		fsa.generateFile("org/mdsd/lorescript/generated/" + loreScript.name + ".java", loreScript.compile(scenarios));
	}
	
	private def compile(LoreScript ls, List<Scenario> scenarios) '''
		package org.mdsd.lorescript.generated;
		import java.util.ArrayList;
		import java.util.List;
		
		public class «ls.name» {
			private LoreScriptScenario currentScenario;
			private LoreScriptEvent next;
			private List<LoreScriptScenario> scenarios = new ArrayList<LoreScriptScenario>();
			
			public «ls.name»() {
				«FOR s : scenarios»
					LoreScriptScenario «s.name.toLowerCase» = new LoreScriptScenario("«s.name»");
					«FOR e : s.events»
						«IF e.type instanceof InformationEvent»
							«val ie = e.type as InformationEvent»
								«IF ie.goto === null»
									«s.name.toLowerCase».addEvent(new LoreScriptInformationEvent("«e.name»", «compileStringExp(ie.text)», null, null));
								«ELSEIF ie.goto.transitionScenario === null»
									«s.name.toLowerCase».addEvent(new LoreScriptInformationEvent("«e.name»", «compileStringExp(ie.text)», null, "«ie.goto.transitionEvent»"));
								«ELSE»
									«s.name.toLowerCase».addEvent(new LoreScriptInformationEvent("«e.name»", «compileStringExp(ie.text)», "«ie.goto.transitionScenario.name»", "«ie.goto.transitionEvent»"));
								«ENDIF»
						«ELSEIF e.type instanceof ChoiceEvent»
							«val ce = e.type as ChoiceEvent»
								LoreScriptOption[] «e.name.toLowerCase»Options = {«FOR o : ce.options SEPARATOR ", "» new LoreScriptOption(«compileStringExp(o.text)», «IF o.goto.transitionScenario !== null»"«o.goto.transitionScenario.name»"«ELSE»null«ENDIF», "«o.goto.transitionEvent»")«ENDFOR»};
								«s.name.toLowerCase».addEvent(new LoreScriptChoiceEvent("«e.name»", «compileStringExp(ce.text)», «e.name.toLowerCase»Options));
						«ENDIF»
					«ENDFOR»
					scenarios.add(«s.name.toLowerCase»);
				«ENDFOR»
				
				currentScenario = scenarios.get(0);
				next = currentScenario.getEvent(0);
			}
			
			public void run() {
				while (next != null)
					next.run(this);
			}
			
			public void setNext(String nextEventName) {
				if (nextEventName == null) {
					next = null;
					return;
				}
				
				next = currentScenario.getEvent(nextEventName);
			}
			
			public void setNext(String nextScenarioName, String nextEventName) {
				for (LoreScriptScenario s : scenarios) {
					if (s.name.equals(nextScenarioName)) {
						currentScenario = s;
						next = s.getEvent(nextEventName);
						return;
					}
				}
			}
		}
	'''
	
	private def compileEventCommon (LoreScript ls) '''
		package org.mdsd.lorescript.generated;
		
		public abstract class LoreScriptEvent {
			String name;
			String text;
			
			public LoreScriptEvent(String name, String text) {
				this.name = name;
				this.text = text;
			}
			
			public abstract void run(«ls.name» ls);
		}
	'''
	
	private def compileScenarioCommon (LoreScript ls) '''
		package org.mdsd.lorescript.generated;
		import java.util.ArrayList;
		import java.util.List;
		
		public class LoreScriptScenario {
			String name;
			private List<LoreScriptEvent> events = new ArrayList<LoreScriptEvent>();
			
			public LoreScriptScenario (String name) {
				this.name = name;
			}
			
			public void addEvent(LoreScriptEvent event) {
				events.add(event);
			}
			
			public LoreScriptEvent getEvent(String name) {
				for (LoreScriptEvent lse : events) {
					if (lse.name.equals(name)) {
						return lse;
					}
				}
				return null;
			}
			
			public LoreScriptEvent getEvent(int index) {
				return events.get(index);
			}
		}
	'''
	
	private def compileInformationEvent (LoreScript ls) '''
		package org.mdsd.lorescript.generated;
		
		public class LoreScriptInformationEvent extends LoreScriptEvent {
			private String transitionScenario = null;
			private String transitionEvent = null;
			
			public LoreScriptInformationEvent(String name, String text, String transitionScenario, String transitionEvent) {
				super(name, text);
				this.transitionScenario = transitionScenario;
				this.transitionEvent = transitionEvent;
			}
			
			@Override
			public void run(«ls.name» ls) {
				System.out.println(text);
				
				if (transitionScenario == null) {
					ls.setNext(transitionEvent);
				}
				else {
					ls.setNext(transitionScenario, transitionEvent);
				}
			}
		}
	'''
	
	private def compileChoiceEvent(LoreScript ls) '''
		package org.mdsd.lorescript.generated;
		import java.util.Scanner;
			
		public class LoreScriptChoiceEvent extends LoreScriptEvent {
			LoreScriptOption[] options;
			
			public LoreScriptChoiceEvent(String name, String text, LoreScriptOption[] options) {
				super(name, text);
				this.options = options;
			}
			
			@Override
			public void run(«ls.name» ls) {
				Scanner scanner = new Scanner(System.in);
				
				System.out.println(text);
				for (int i = 0; i < options.length; i++) {
					System.out.println("["+(i+1)+"] " + options[i].text);
				}
				
				int choice = 0;
				while(true) {
					try {
						choice = Integer.parseInt(scanner.nextLine());
						String transitionScenario = options[choice-1].transitionScenario;
						String transitionEvent = options[choice-1].transitionEvent;
						
						if (transitionScenario == null) {
							ls.setNext(transitionEvent);
						}
						else {
							ls.setNext(transitionScenario, transitionEvent);
						}
						break;
					}
					catch (NumberFormatException e) {
						System.out.println("Your answer must be a number!");
					}
					catch (ArrayIndexOutOfBoundsException  e) {
						System.out.println("Your answer was not a valid option!");
					}
				}
			}
		}
	'''
	
	private def compileOption() '''
		package org.mdsd.lorescript.generated;
		
		public class LoreScriptOption {
			public String text;
			public String transitionScenario;
			public String transitionEvent;
			public LoreScriptOption(String text, String transitionScenario, String transitionEvent) {
				this.text = text;
				this.transitionScenario = transitionScenario;
				this.transitionEvent = transitionEvent;
			}
		}
	'''
	
	def CharSequence compileStringExp(StringExp exp) {
	    switch exp {
	    	StringLiteral:
	            '''"«exp.value»"'''
	            
	        ConcatExp:
	        	'''«compileStringExp(exp.left)» + «compileStringExp(exp.right)»'''
	        	
	        MultiplyExp: {
	            val repeated = (1 .. exp.multiplier)
	                .map[compileStringExp(exp.left).toString]
	                .join(" + ")
	
	            '''(«repeated»)'''
        	}
	        default:
	            '''""'''
	    }
	}
}
