/*
 * generated by Xtext 2.32.0
 */
package org.mdsd.lorescript.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class LoreScriptProposalProvider extends AbstractLoreScriptProposalProvider {
}
