/*
 * generated by Xtext 2.32.0
 */
package org.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LoreScriptUiModule extends AbstractLoreScriptUiModule {

	public LoreScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
