grammar org.mdsd.lorescript.LoreScript with org.eclipse.xtext.common.Terminals

generate loreScript "http://www.mdsd.org/lorescript/LoreScript"

LoreScript:
    'lorescript' name=ID scenarios+=Scenario*
;

Scenario:
	'scenario' name=ID '{'events+=Event*'}'
;

Event:
    'event' name=ID '{'type=EventType'}'
;

EventType:
    InformationEvent | ChoiceEvent
;

InformationEvent:
    'text:'text=StringExp (goto=Goto)?
;

ChoiceEvent:
    'text:'text=StringExp options+=Option+
;

Option:
    'option''{''text:'text=StringExp goto=Goto'}'
;

Goto:
	('goto:' | '->') transition=[Event]
;

StringExp:
	StringLiteral ({StringExp.left=current} '+' right=StringLiteral)*
;

StringLiteral:
	{StringLiteral} value=STRING
;