grammar org.mdsd.lorescript.LoreScript with org.eclipse.xtext.common.Terminals

generate loreScript "http://www.mdsd.org/lorescript/LoreScript"

LoreScript:
    'lorescript' name=ID scenarios+=Scenario*
;

Scenario:
	'scenario' name=ID '{'events+=Event*'}'
;

Event:
    'event' name=ID '{'type=EventType'}'
;

EventType:
    InformationEvent | ChoiceEvent
;

InformationEvent:
    'text:'text=StringExp (triggers+=Trigger)* (goto=Goto)?
;

ChoiceEvent:
    'text:'text=StringExp options+=Option+
;

Option:
    'option''{''text:'text=StringExp (triggers+=Trigger)* goto=Goto'}'
;

//These ID's for transitionEvent should ideally be [Event] references. However this requires 
//custom scoping or a custom qualified name provider, which is out of scope for the group project.
Goto:
	('goto:' | '->') (transitionEvent=[Event] | transitionScenario=[Scenario] '.' transitionEvent=[Event])
;

Trigger:
	'trigger' function=ID '('(params+=Param (',' params+=Param)*)?')'
;

Param:
	StringParam | IntParam | BoolParam
;

StringParam:
	value=STRING
;

IntParam:
	value=INT
;

BoolParam:
	value=('TRUE' | 'FALSE' | 'true' | 'false')
;

StringExp:
	ConcatExp
;

ConcatExp returns StringExp:
    MultiplyExp ({ConcatExp.left=current} '+' right=MultiplyExp)*
;

MultiplyExp returns StringExp:
    PrimaryExp ({MultiplyExp.left=current} '*' multiplier=INT)*
;

PrimaryExp returns StringExp:
	StringLiteral | GetFunction
;

StringLiteral returns StringExp:
	{StringLiteral} value=STRING
;

GetFunction returns StringExp:
	{GetFunction} '$' request=ID
;