/*
 * generated by Xtext 2.32.0
 */
package org.mdsd.lorescript;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LoreScriptStandaloneSetup extends LoreScriptStandaloneSetupGenerated {

	public static void doSetup() {
		new LoreScriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
